
trigger:
- main

pool:
  name: Default

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - script: echo Build FirstJob
  - job: SecondJob
    steps:
    - script: echo Build SecondJob
- stage: DevDeploy
  jobs:
  - job: DevDeployJob
    steps:
    - script: echo DevDeployJob
- stage: QADeploy
  jobs:
  - job: QADeployJob
    steps:
    - script: echo QADeployJob
- stage: ProdDeploy
  jobs:
  - job: ProdDeployJob
    steps:
    - script: echo ProdDeployJob
